version: '3'

services:
  db:
    image: mongo
    restart: always
    ports: [27017:27017]
    volumes:
      - 'db:/data/db'

  app:
    build: ./app
    restart: always
    ports: [3000:3000]
    environment:
      - DB_HOST=mongodb://db:27017/posts
    depends_on:
      - db
volumes:
  db: 